[package]
name = "sdf-view"
version = "0.1.1"
edition = "2024"

[workspace]
resolver = "3"
members = ["cli"]
default-members = [".", "cli"]

[dependencies]
futures = { version = "0.3.34", default-features = false, features = ["executor", "std"] }
thiserror = "2.0.21"
wgpu = { version = "30.0.1", features = ["glsl"] }
