[package]
name = "sdf-view-cli"
version = "0.1.1"
edition = "2024"

[[bin]]
doc = false
name = "sdf-view"
path = "src/main.rs"

[dependencies]
clap = { version = "4.6.7", features = ["derive"] }
futures = { version = "0.3", optional = true }
glam = { version = "0.32", optional = true }
png = "0.18.1"
sdf-view = { path = "..", version = "0.1.1", default-features = false }
thiserror = "2.0.21"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
wgpu = { version = "30", optional = true }
winit = { version = "0.30", optional = true }

[features]
default = ["gpu-test", "interactive"]
gpu-test = ["sdf-view/gpu-test"]
interactive = ["dep:futures", "dep:glam", "dep:wgpu", "dep:winit"]
